name: ci

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Stop old builds
        if: github.ref != 'refs/heads/master'
        uses: styfle/cancel-workflow-action@0.4.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11     
      - name: Build & Test
        run: ./mvnw -B verify
